### ISSUE TITLE
Mechanizm wyboru interfejsu

### ISSUE THREAD

**Issue by Jeeejeets** [akai-org/joystick_monorepo#36]
Mamy okodowany formularz rejestracji gracza. W odpowiedzi na rejestrację gracza dostajemy adres ws i nazwę interfejsu. Na podstawie otrzymanej nazwy interfejsu musimy wybrać odpowiedni interfejs i wyświetlić go graczowi. Dobrze by było, jeżeli cały interfejs będzie się mieścił na jednej podstronie, tzn. bez tworzenia osobnej podstrony dla interfejsu A, B, C etc. tak, aby dodanie nowego interfejsu było możliwe jak najprostsze. Do przemyślenia jak to dokładnie zrobić.

**Comment by Gumkle** [comment]
- oddzielny path do interfejsu (joystick.pl/game, interface)

**Comment by Gumkle** [comment]
`inteface-arrows-horizontal` => `IntefaceArrowsHorizontal.vue`

**Comment by Gumkle** [comment]
arrows-horizontal
arrows-vertical
arrows-vertical-1ab -- jest w trakcie
cross-arrows -- nie ma jeszcze interfejsu
cross-arrows-1ab -- nie ma jeszcze interfejsu
