### ISSUE TITLE
Identyfikacja graczy

### ISSUE THREAD

**Issue by Gumkle** [akai-org/joystick_monorepo#37]
W obrębie jednej gry (pokoju) gracze mogą dostawać swoje unikatowe IDki. Te IDki będą przesyłane do gry razem z informacją o tym, jakie akcje wykonał gracz. 

Odebrane od joysticka jednobajtowe informacje nt klikniete przycisku poszerzyć o jednobajtowy identyfikator przypisany do gracza.

**Comment by MrSydar** [comment]
todo:
- add uuid field to player
- return uuid instead of 'Address' on registration
