### ISSUE TITLE
Opcja --verbose do serwera go

### ISSUE THREAD

**Issue by Gumkle** [akai-org/joystick_monorepo#9]
Dobrze, jeżeli serwer będzie można odpalić z opcją --verbose w celu debugowania. To może się przydać dla backendu i frontendu:
- dodać obsługę flagi --verbose,
- dodać logger, który w zależności obecności tej opcji w komendzie uruchamiającej będzie printował informacje do konsoli lub nie, 

Może warto pomyśleć o załączaniu loggera za pomocą zmiennej środowiskowej? Np kiedy ENVIRONMENT=development, to wtedy logger printuje pełną informację? Do przemyślenia

**Comment by afilipkowski** [comment]
https://pkg.go.dev/flag - paczka dot flag, to znaczy opcji --verbose
https://pkg.go.dev/log - paczka dot logów

Utworzenie abstrakcji na logger. Użycie loggera w aplikacji. Inicjowanie null loggera przy braku opcji verbose.
